SELECT 
DAI.DAI_FILIAL, 
DAI.DAI_COD, 
DAI.DAI_DATA, 
DA5_DESC,
DAI.DAI_PEDIDO,
DA4.DA4_NOME MOTORISTA, 
DAI.DAI_CLIENT,
A1.A1_NOME, 
DAI.DAI_PESO, 
ISNULL(
    (SELECT E1.E1_VALOR 
     FROM SE1070 E1 
     WHERE  
     E1.E1_FILIAL = DAI.DAI_FILIAL AND 
     E1.E1_CLIENTE = DAI.DAI_CLIENT AND 
     E1.E1_LOJA = DAI.DAI_LOJA AND
     E1.E1_PREFIXO = DAI.DAI_SERIE AND 
     E1.E1_NUM = DAI.DAI_NFISCA AND 
     E1.E1_PARCELA = '  ' AND
     E1.E1_TIPO = 'NF ' AND
     E1.D_E_L_E_T_ = ' '), 0) AS VALOR,
DAI.DAI_NFISCA, 
DAI.DAI_SERIE,
CASE
    WHEN DAK.DAK_CAMINH = 'KHA0902' THEN 'Cliente'
    ELSE DAK.DAK_CAMINH
END CAMINHAO,
CASE
    WHEN DAK.DAK_ACECAR IN ('7','8') THEN 'Fechada'
    ELSE 'Aberta'
END STATUS 
FROM DAI070 DAI
INNER JOIN DAK070 DAK ON DAK.DAK_FILIAL = DAI.DAI_FILIAL AND DAK.DAK_COD = DAI.DAI_COD AND DAK.DAK_SEQCAR = DAI.DAI_SEQCAR AND DAK.DAK_DATA >= :DATA_INICO AND DAK.DAK_DATA <= :DATA_FIM AND DAK.DAK_ACECAR IN (:STATUS_CARGA) AND DAK.D_E_L_E_T_ = ' '   
INNER JOIN SA1070 A1 ON A1.A1_FILIAL = DAI.DAI_FILIAL AND A1.A1_COD = DAI.DAI_CLIENT AND A1.A1_LOJA = DAI.DAI_LOJA AND A1.D_E_L_E_T_ = ' ' 
LEFT JOIN DA4070 DA4 ON DA4.DA4_FILIAL = DAK.DAK_FILIAL AND DA4.DA4_COD = DAK.DAK_MOTORI AND DA4.D_E_L_E_T_ = ' ' 
LEFT JOIN DA5070 DA5 ON DA5.DA5_FILIAL = DAI.DAI_FILIAL AND DA5.DA5_COD = DAI.DAI_PERCUR AND DA5.D_E_L_E_T_ = ' ' 
WHERE DAI.DAI_SEQUEN <> '999999' AND DAI.D_E_L_E_T_ = ' ' 
ORDER BY DAI.DAI_FILIAL, DAI.DAI_COD, DAI.DAI_SEQCAR