SELECT 
TMP.FILIAL, 
TMP.DIA, 
TMP.CODIGO, 
TMP.DESCRICAO, 
SUM(TMP.QTDE) QTDE, 
SUM(TMP.FATURAMENTO)/SUM(TMP.QTDE) PRECO_MEDIO,
SUM(TMP.FATURAMENTO) FATURAMENTO, 
SUM(TMP.CUSTO) CUSTO, 
SUM(TMP.FATURAMENTO)-SUM(TMP.CUSTO) LUCRO_BRUTO, 
((SUM(TMP.FATURAMENTO)-SUM(TMP.CUSTO))/SUM(TMP.FATURAMENTO))*100 MARGEM_BRUTA
FROM (SELECT 
    D2.D2_FILIAL FILIAL, 
    DAY(D2.D2_EMISSAO) DIA, 
    D2.D2_COD CODIGO, 
    B1.B1_DESC DESCRICAO, 
    (D2.D2_QUANT/B1.B1_CONV) QTDE,
    CASE 
        WHEN D2.D2_YOPER IN ('542','543','544') THEN 0   -- bonificacoes
        WHEN D2.D2_YOPER IN ('501') THEN D2.D2_TOTAL    -- vendas
        ELSE 0
    END FATURAMENTO,
    D2.D2_CUSTO1 CUSTO, 
    (D2.D2_TOTAL-D2.D2_CUSTO1) LUCRO_BRUTO
FROM SD2070 D2
INNER JOIN SB1000 B1 ON B1.D_E_L_E_T_ = ' ' AND B1.B1_FILIAL = '  ' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA'
WHERE D2.D_E_L_E_T_ = ' ' AND D2.D2_EMISSAO >= :DATA_INICIAL AND D2.D2_EMISSAO <= :DATA_FINAL AND D2.D2_YOPER IN ('501','542','543','544')) TMP
GROUP BY TMP.FILIAL, TMP.DIA, TMP.CODIGO, TMP.DESCRICAO
ORDER BY TMP.FILIAL, TMP.DIA, TMP.CODIGO, TMP.DESCRICAO
 