SELECT DAI.DAI_FILIAL, DAI.DAI_COD, DAI.DAI_DATA, DAI.DAI_PEDIDO, DAI.DAI_CLIENT, DAI.DAI_PESO, DAI.DAI_NFISCA, DAK.DAK_CAMINH, DAK.DAK_ACECAR, A1.A1_NOME, DAK.DAK_VALOR
FROM DAI070 DAI
INNER JOIN DAK070 DAK ON DAK.D_E_L_E_T_ = ' ' AND DAK.DAK_FILIAL = DAI.DAI_FILIAL AND DAK.DAK_COD = DAI.DAI_COD AND DAK.DAK_SEQCAR = DAI.DAI_SEQCAR 
INNER JOIN SA1070 A1 ON A1.D_E_L_E_T_ = ' ' AND A1.A1_FILIAL = DAI.DAI_FILIAL AND A1.A1_COD = DAI.DAI_CLIENT AND A1.A1_LOJA = DAI.DAI_LOJA 
WHERE DAI.D_E_L_E_T_ = ' '  AND DAI.DAI_DATA >= '20260801' AND DAI.DAI_SEQUEN <> '999999'
ORDER BY DAI.DAI_FILIAL, DAI.DAI_COD, DAI.DAI_SEQCAR