SELECT 
TMP.FILIAL, TMP.DIA, TMP.CODIGO, TMP.DESCRICAO, SUM(TMP.QTDE) QTDE, SUM(TMP.FATURAMENTO) FATURAMENTO, AVG(TMP.PRECO_MEDIO) PRECO_MEDIO,SUM(TMP.LUCRO_BRUTO) LUCRO_BRUTO, (SUM(TMP.LUCRO_BRUTO)/SUM(TMP.FATURAMENTO))*100 MARGEM
FROM (SELECT 
    D2.D2_FILIAL FILIAL, 
    DAY(D2.D2_EMISSAO) DIA, 
    D2.D2_COD CODIGO, 
    B1.B1_DESC DESCRICAO, 
    CASE 
        WHEN D2.D2_YOPER IN ('542','543','544') THEN 0
        WHEN D2.D2_YOPER IN ('501') THEN (D2.D2_QUANT/B1.B1_CONV)
        ELSE 0
    END QTDE,
    D2.D2_TOTAL FATURAMENTO,
    AVG(D2.D2_TOTAL/(D2.D2_QUANT/B1.B1_CONV)) PRECO_MEDIO,
    (D2.D2_TOTAL-D2.D2_CUSTO1) LUCRO_BRUTO, 
    ((D2.D2_TOTAL-D2.D2_CUSTO1)/D2.D2_TOTAL)*100 MARGEM 
FROM SD2070 D2
INNER JOIN SB1000 B1 ON B1.D_E_L_E_T_ = ' ' AND B1.B1_FILIAL = '  ' AND B1.B1_COD = D2.D2_COD AND B1.B1_TIPO = 'PA'
WHERE D2.D_E_L_E_T_ = ' ' AND D2.D2_EMISSAO >= :DATA_INICIO AND D2.D2_EMISSAO <= :DATA_FIM AND D2.D2_YOPER IN ('501','542','543','544')
GROUP BY D2.D2_FILIAL, DAY(D2.D2_EMISSAO), D2.D2_COD, B1.B1_DESC, D2.D2_YOPER, D2.D2_QUANT, B1.B1_CONV, D2.D2_TOTAL, D2.D2_CUSTO1) TMP
GROUP BY TMP.FILIAL, TMP.DIA, TMP.CODIGO, TMP.DESCRICAO
